version: "3.7"

services:
  ad-service-db-pg:
    build:
      context: ./build/db
      target: ad-service-db-pg
    image: ad-service-db-pg:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    container_name: ad-service-db-pg

  ad-service-app:
    build:
      context: ./build/app
      target: ad-service-app
    image: ad-service-app:latest
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - APP_PORT=8000
      - DB_HOST=ad-service-db-pg
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DBNAME=postgres
      - DB_SSL=disable
    depends_on:
      - ad-service-db-pg

    container_name: ad-service-app
